# Generated by Django 2.2.5 on 2019-09-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapist', '0001_initial'),
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.Therapist'),
        ),
        migrations.AddField(
            model_name='performance',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.GameSession'),
        ),
        migrations.AddField(
            model_name='performance',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Movement'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='movements',
            field=models.ManyToManyField(to='start.Movement'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='minigame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Minigame'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='movements',
            field=models.ManyToManyField(through='start.Performance', to='start.Movement'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.TherapySession'),
        ),
    ]
