# Generated by Django 2.2.5 on 2019-09-24 04:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=64, verbose_name='Apellido')),
                ('id_type', models.CharField(choices=[('Cédula de ciudadania', 'Cédula de ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Número de pasaporte', 'Número de pasaporte'), ('Cédula de extranjeria', 'Cédula de extranjeria')], max_length=64, verbose_name='Tipo de identificación')),
                ('genre', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=64, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
