# Generated by Django 2.2.5 on 2019-09-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('Cédula de ciudadania', 'Cédula de ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Número de pasaporte', 'Número de pasaporte'), ('Cédula de extranjeria', 'Cédula de extranjeria')], max_length=64)),
                ('id_num', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('genre', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Entity')),
                ('list_diagnostic', models.ManyToManyField(to='patients.Diagnostic')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='type_diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.TypeDiagnostic'),
        ),
    ]
