# Generated by Django 2.2.5 on 2019-10-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20190930_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='list_diagnostic',
        ),
        migrations.AddField(
            model_name='patient',
            name='list_diagnostic',
            field=models.ManyToManyField(to='patients.Diagnostic'),
        ),
    ]
