# Generated by Django 2.2.5 on 2019-10-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20190930_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.CharField(max_length=64),
        ),
    ]
