# Generated by Django 2.2.5 on 2019-10-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20190930_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='list_diagnostic',
        ),
        migrations.AddField(
            model_name='patient',
            name='list_diagnostic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patients.Diagnostic'),
            preserve_default=False,
        ),
    ]
